[tool.pylint.MAIN]

max-line-length = 100

[tool.pylint.'MESSAGES CONTROL']

disable = [
    "invalid-name",
    "missing-function-docstring",
    "missing-class-docstring"
]

[tool.black]

line-length = 100
